#!/usr/bin/python

from backend import application

from wsgiref.simple_server import make_server
	
host = '127.0.0.1'
port = 8080

httpd = make_server(host, port, application)
print("Serving on port {}...".format(port))
httpd.serve_forever()