angular.module('MatWeb', [
  'ngRoute',
  'nucleo',
  'Cadastrar',
  'Cadastrarcurso',
  'Cadastrarusuario',
  'Home',
  'Usuario',
  'Oferta',
  'Campus',
  'Predio',
  'Departamento',
  'Registrodesala',
  'Curso',
  'ui.bootstrap',
]);
